name: validations
description: Validations for dart models.
version: 0.9.2
homepage: https://github.com/hx-ai/validations
authors:
  - Rob Halff <rob.halff@gmail.com>
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  decimal: '>=0.3.3'
  meta: '>=1.0.0'
  intl: '>=0.16.1'
  validators: '>=2.0.0'

dev_dependencies:
  coverage: ^0.12.4
  build_runner: ^1.9.0
  pedantic: ^1.0.0
  test: ^1.8.0
  test_coverage: ^0.3.0+1
