name: validations
description: Validations for dart models.
version: 1.0.0
homepage: https://github.com/dartlib/validations.git
authors:
  - Rob Halff <rob.halff@gmail.com>
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  decimal: ^0.3.5
  meta: ^1.2.4
  intl: ^0.16.1
  validators: ^2.0.1

dev_dependencies:
  validations_generator:
    git:
      url: https://github.com/hx-ai/validations
      path: validations_generator
  coverage: ^0.13.0
  build_runner: ^1.10.6
  pedantic: ^1.9.2
  test: ^1.15.7
  test_coverage: ^0.4.2
