name: validations_generator
version: 1.0.0
description: Generator for the validations package.
authors:
- Rob Halff <rob.halff@gmail.com>
homepage: https://github.com/hx-ai/validations

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  validations:
    git:
      url: https://github.com/hx-ai/validations
      path: validations
  analyzer: ^0.40.6
  build: ^1.5.1
  build_config: ^0.4.3
  logging: ^0.11.4
  source_gen: ^0.9.8
  code_builder: ^3.5.0
  dart_style: ^1.3.10
  meta: ^1.2.4

dev_dependencies:
  decimal: ^0.3.5
  pedantic: ^1.9.2
  test: ^1.15.7
  build_runner: ^1.10.6
  intl: ^0.16.1
  build_test: ^1.3.0
  collection: ^1.14.13
